# Generated by Django 2.2.4 on 2019-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sighting',
            name='latitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='longitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='species',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
